{
 "title": "Networks",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "wrt_interface_bytes_rate/(1024)",
     "legendFormat": "Roteador - {{direction}}"
    }
   ]
  },
  {
   "title": "Rede local",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sum by(instance, direction) (huawei_network_traffic_rate)",
     "legendFormat": "AX3 PRO {{direction}}"
    }
   ]
  },
  {
   "title": "Rede local - hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    { "expr": "huawei_network_traffic_rate", "legendFormat": "{{host}} - {{direction}}" }
   ]
  },
  {
   "title": "Uso da rede - Download ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "huawei_network_traffic_count{direction=\"rx\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Uso da rede - Upload",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "huawei_network_traffic_count{direction=\"tx\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Uso da rede - Total",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (huawei_network_traffic_count)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}